[project]
name = "mt-levy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.1",
    "hydra-core>=1.3.2",
    "metaworld>=3.0.0",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "wandb>=0.22.0",
]
