num_neighbors: 5
alpha_offset: 1
sr_threshold: 0.1
builder:
  _target_: mt_levy.exploration_strategies.MTLevy
  seed: ${seed}
  num_tasks: ${environment.num_envs}
  horizon: ${environment.horizon}
  alpha_offset: ${exploration_strategy.alpha_offset}
  sr_threshold: ${exploration_strategy.sr_threshold}
  num_neighbors: ${exploration_strategy.num_neighbors}