seed: 0
gpu_index: 0

training:
  num_epochs: 200
  train_steps: 10000
  init_steps: 1000
  batch_size: 128

evaluation:
  num_episodes: 10

logging:
  use_wandb: True
  log_interval: 100
  ckpt_interval: 20
  ckpt_base_dir: ../sdc/ckpts

wandb:
  project: iros25
  name: SAC
  mode: online

environment:
  benchmark: reach-v2
  obs_dim: 39
  act_dim: 4
  sparse: False
  horizon: 150

agent:
  algo: sac
  builder:
    _target_: algos.sac.SAC
    obs_dim: ${environment.obs_dim}
    act_dim: ${environment.act_dim}
    actor_cfg: ${agent.actor}
    actor_optim_cfg: ${agent.actor_optimizer}
    critic_cfg: ${agent.critic}
    critic_optim_cfg: ${agent.critic_optimizer}
    temp_optim_cfg: ${agent.temperature_optimizer}
    init_temp: 0.1
    gamma: 0.99
    tau: 0.005
    gpu_index: ${gpu_index}
  actor:
    _target_: components.actor.Actor
    hidden_dim: 400
    num_layers: 3
    log_std_max: 2
    log_std_min: -20
  actor_optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  critic:
    _target_: components.critic.Critic
    hidden_dim: 400
    num_layers: 3
    bound: ${environment.sparse}
  critic_optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  temperature_optimizer:
    _target_: torch.optim.Adam
    lr: 0.0001

buffer:
  _target_: buffers.replay_buffer.ReplayBuffer
  capacity: 1000000
  obs_dim: ${environment.obs_dim}
  act_dim: ${environment.act_dim}
  seed: ${seed}