top_n: 5
alpha_lower_bound: 3
builder:
  _target_: exp_strategy.MTLevy
  num_tasks: ${environment.num_envs}
  top_n: ${exploration_strategy.top_n}
  alpha_lower_bound: ${exploration_strategy.alpha_lower_bound}
  seed: ${seed}