seed: 0
gpu_index: 0

training:
  num_epochs: 200
  train_steps: 10000
  init_steps: 1000
  batch_size: 1280
  sr_decay: 0.01

evaluation:
  num_episodes: 10

logging:
  use_wandb: True
  log_interval: 100
  ckpt_interval: 20
  ckpt_base_dir: ../sdc/ckpts

wandb:
  project: iros25
  name: MTMHSAC
  mode: online

environment:
  benchmark: MT10
  num_envs: 10
  obs_dim: 39
  act_dim: 4
  sparse: False
  horizon: 150

agent:
  algo: mtmhsac
  builder:
    _target_: algos.mtmhsac.MTMHSAC
    num_envs: ${environment.num_envs}
    obs_dim: ${environment.obs_dim}
    act_dim: ${environment.act_dim}
    actor_cfg: ${agent.actor}
    actor_optim_cfg: ${agent.actor_optimizer}
    critic_cfg: ${agent.critic}
    critic_optim_cfg: ${agent.critic_optimizer}
    temp_optim_cfg: ${agent.temperature_optimizer}
    init_temp: 0.1
    gamma: 0.99
    tau: 0.005
    gpu_index: ${gpu_index}
  actor:
    _target_: components.actor.MultiHeadActor
    hidden_dim: 400
    num_trunk_layers: 3
    num_heads: ${environment.num_envs}
    num_head_layers: 2
    log_std_max: 2
    log_std_min: -20
  actor_optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  critic:
    _target_: components.critic.MultiHeadCritic
    hidden_dim: 400
    num_trunk_layers: 3
    num_heads: ${environment.num_envs}
    num_head_layers: 2
    bound: ${environment.sparse}
  critic_optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  temperature_optimizer:
    _target_: torch.optim.Adam
    lr: 0.0001

buffer:
  buffer_size: 1000000